queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - "check-success=Build and Test"

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "check-success=Build and Test"
    actions:
      queue:
        name: default
        method: rebase
