[package]
name = "powerline"
version = "0.2.0"
authors = ["Xeoeen <Xeoeen@users.noreply.github.com>"]
edition = "2018"

[dependencies]
users = "0.9"
libc = "0.2"
hostname = "0.1.5"

[features]
default = ["bare-shell"]
bash-shell = []
bare-shell = []
zsh-shell = []

[profile.release]
opt-level = 3
lto = true
debug = false
