[package]
name = "powerline"
version = "0.1.0"
authors = ["Xeoeen <Xeoeen@users.noreply.github.com>"]
edition = "2018"

[dependencies]
users = "0.9"
libc = "0.2"


[features]
default = ["bash-colors"]
bash-colors = []
bare-colors = []

[profile.release]
opt-level = 3
lto = true
debug = false
