[package]
name = "powerline"
version = "0.2.0"
authors = ["Xeoeen <Xeoeen@users.noreply.github.com>"]
edition = "2018"

[dependencies]
users = "0.9"
libc = "0.2"
miniserde = { version = "0.1.12", optional = true }
hostname = "0.1.5"

[features]
default = ["zsh-shell", "git-file-cache"]
bash-shell = []
bare-shell = []
zsh-shell = []
git-file-cache = ["miniserde"]

[profile.release]
opt-level = 3
lto = true
debug = false
