name: Build and Test

on:
  push:
    paths-ignore:
      - "*.md"
      - LICENSE
      - rustfmt.toml
      - examples/**
      - .github/dependabot.yml
      - .github/workflows/pull_requests.yml
      - .gitigore
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Install kcov
        run: sudo apt-get update && sudo apt-get install cmake g++ pkg-config jq  libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev libiberty-dev -y
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install kcov cargo
        run: cargo install cargo-kcov
      - name: Install kcov
        run: cargo kcov --print-install-kcov-sh | sh
      - name: Build
        run: cargo build --release --all-features
      - name: Test
        run: cargo kcov
      - uses: codecov/codecov-action@v1
        if: always()
  make_multiarch:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - arm-unknown-linux-musleabihf
    name: Make multi-arch binaries
    if: github.event_name != 'pull_request'
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build bare version
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: true
          args: --release --target=${{ matrix.target }} --no-default-features --features=bare-shell,libgit,cli-options,time
      - name: rename bare binary
        run: mv target/$TARGET/release/powerline target/$TARGET/release/powerline-bare
        env:
          TARGET: ${{ matrix.target }}
      - name: Build bash version
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: true
          args: --release --target=${{ matrix.target }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: target/**/release/powerline*
  package:
    name: Build deb packages
    if: github.event_name != 'pull_request'
    needs: make_multiarch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: target
      - name: Set up Ruby 2.5
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: Install gems
        run: |
          gem install fpm -v 1.11.0
      - name: Make deb package
        run: |
          export DEB_VERSION="$(cat Cargo.toml | grep "^version = " | awk  '{gsub(/"/, "", $3); print $3}')-$(printf "%04d" $GITHUB_RUN_NUMBER)"
          echo $DEB_VERSION
          find . -type f \( -name "powerline" -o -name "powerline-bare" \) -exec chmod +x {} \;
          fpm -f -s dir -t deb --deb-priority optional --maintainer github@growse.com --vendor github@growse.com --license MIT -n $DEB_NAME --description "$APPDESCRIPTION" --url $APPURL --prefix / -a amd64 -v $DEB_VERSION ./x86_64-unknown-linux-musl/release/powerline=/usr/bin/powerline-rust ./x86_64-unknown-linux-musl/release/powerline-bare=/usr/bin/powerline-rust-bare
          fpm -f -s dir -t deb --deb-priority optional --maintainer github@growse.com --vendor github@growse.com --license MIT -n $DEB_NAME --description "$APPDESCRIPTION" --url $APPURL --prefix / -a armhf -v $DEB_VERSION ./arm-unknown-linux-musleabihf/release/powerline=/usr/bin/powerline-rust ./arm-unknown-linux-musleabihf/release/powerline-bare=/usr/bin/powerline-rust-bare
        env:
          DEB_NAME: powerline-rust
          APPDESCRIPTION: powerline-shell written in Rust
          APPURL: https://github.com/growse/powerline-rust
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: debfiles
          path: "*.deb"
      - name: Upload to Apt repo
        env:
          APT_KEY_PASSPHRASE: ${{ secrets.APT_KEY_PASSPHRASE }}
          APT_CREDENTIALS: ${{ secrets.APT_CREDENTIALS }}
        run: |
          echo $APT_CREDENTIALS > aptly-auth
          find -maxdepth 1 -name "*.deb" -exec curl -f --netrc-file aptly-auth -XPOST -F file=@{} https://apttoo.growse.com/api/files/powerline \;
          export result=$(curl -f --netrc-file aptly-auth -X POST https://apttoo.growse.com/api/repos/defaultrepo/file/powerline)
          echo $result
          export failed=$(echo $result | jq '.FailedFiles | length')
          if [[ "$failed" != "0" ]]; then exit 1; fi
          curl -f --netrc-file aptly-auth -X PUT -H"Content-type: application/json" --data '{"Signing":{"Passphrase":"'"$APT_KEY_PASSPHRASE"'","Batch":true}}' https://apttoo.growse.com/api/publish/:./stablish

